ALTER TABLE `locazioni` ADD v01 INT DEFAULT 3
ALTER TABLE `locazioni` ADD v02 INT DEFAULT 3
ALTER TABLE `locazioni` ADD v03 INT DEFAULT 3
ALTER TABLE `locazioni` ADD v04 INT DEFAULT 3
ALTER TABLE `locazioni` ADD v05 INT DEFAULT 3
ALTER TABLE `locazioni` ADD v06 INT DEFAULT 3
ALTER TABLE `locazioni` ADD v07 INT DEFAULT 3
ALTER TABLE `locazioni` ADD v08 INT DEFAULT 3
ALTER TABLE `locazioni` ADD v09 INT DEFAULT 3
ALTER TABLE `locazioni` ADD v10 INT DEFAULT 3
ALTER TABLE `locazioni` ADD v11 INT DEFAULT 3
ALTER TABLE `locazioni` ADD v12 INT DEFAULT 3
ALTER TABLE `locazioni` ADD v13 INT DEFAULT 3
ALTER TABLE `locazioni` ADD v14 INT DEFAULT 3
ALTER TABLE `locazioni` ADD v15 INT DEFAULT 3
ALTER TABLE `locazioni` ADD v16 INT DEFAULT 3
ALTER TABLE `locazioni` ADD v17 INT DEFAULT 3
ALTER TABLE `locazioni` ADD v18 INT DEFAULT 3
ALTER TABLE `locazioni` ADD v19 INT DEFAULT 3
ALTER TABLE `locazioni` ADD v20 INT DEFAULT 3
ALTER TABLE `locazioni` ADD v21 INT DEFAULT 3
ALTER TABLE `locazioni` ADD v22 INT DEFAULT 3
ALTER TABLE `locazioni` ADD v23 INT DEFAULT 3
ALTER TABLE `locazioni` ADD v24 INT DEFAULT 3

ALTER TABLE `locazioni` ADD t01 INT DEFAULT 60
ALTER TABLE `locazioni` ADD t02 INT DEFAULT 60
ALTER TABLE `locazioni` ADD t03 INT DEFAULT 60
ALTER TABLE `locazioni` ADD t04 INT DEFAULT 60
ALTER TABLE `locazioni` ADD t05 INT DEFAULT 60
ALTER TABLE `locazioni` ADD t06 INT DEFAULT 60
ALTER TABLE `locazioni` ADD t07 INT DEFAULT 60
ALTER TABLE `locazioni` ADD t08 INT DEFAULT 60
ALTER TABLE `locazioni` ADD t09 INT DEFAULT 60
ALTER TABLE `locazioni` ADD t10 INT DEFAULT 60
ALTER TABLE `locazioni` ADD t11 INT DEFAULT 60
ALTER TABLE `locazioni` ADD t12 INT DEFAULT 60
ALTER TABLE `locazioni` ADD t13 INT DEFAULT 60
ALTER TABLE `locazioni` ADD t14 INT DEFAULT 60
ALTER TABLE `locazioni` ADD t15 INT DEFAULT 60
ALTER TABLE `locazioni` ADD t16 INT DEFAULT 60
ALTER TABLE `locazioni` ADD t17 INT DEFAULT 60
ALTER TABLE `locazioni` ADD t18 INT DEFAULT 60
ALTER TABLE `locazioni` ADD t19 INT DEFAULT 60
ALTER TABLE `locazioni` ADD t20 INT DEFAULT 60
ALTER TABLE `locazioni` ADD t21 INT DEFAULT 60
ALTER TABLE `locazioni` ADD t22 INT DEFAULT 60
ALTER TABLE `locazioni` ADD t23 INT DEFAULT 60
ALTER TABLE `locazioni` ADD t24 INT DEFAULT 60

ALTER TABLE `locazioni` ADD gEmail VARCHAR(100) DEFAULT 0
ALTER TABLE `locazioni` ADD gSMS VARCHAR(100) DEFAULT 0

ALTER TABLE `locazioni` ADD email01 VARCHAR(100)
ALTER TABLE `locazioni` ADD email02 VARCHAR(100)
ALTER TABLE `locazioni` ADD email03 VARCHAR(100)
ALTER TABLE `locazioni` ADD email04 VARCHAR(100)


ALTER TABLE `locazioni` ADD SMS01 VARCHAR(100)
ALTER TABLE `locazioni` ADD SMS02 VARCHAR(100)
ALTER TABLE `locazioni` ADD SMS03 VARCHAR(100)
ALTER TABLE `locazioni` ADD SMS04 VARCHAR(100)  
